SELECT RMA_PIECE_RCPT_TX_F.RMA_ACT_ID,
       RMA_PIECE_RCPT_TX_F.HOST_ORD_N,
       RMA_PIECE_RCPT_TX_F.RMA_RESHIP_RJCT_KEY,
       RMA_PIECE_RCPT_TX_F.PROOF_OF_PURCH_DT_KEY,
       RMA_PIECE_RCPT_TX_F.RMA_TRACK_N,
       DT_DIM.DT,
       DT_DIM.DT_TY,
       DT_DIM.DAY_OF_WEEK_NM,
       DT_DIM.CAL_YR_DAY_OF_WEEK_N,
       DT_DIM.CAL_YR_DAY_OF_MTH_N,
       DT_DIM.CAL_YR_WEEK_N,
       DT_DIM.CAL_YR_WEEK_NM,
       DT_DIM.CAL_YR_WEEK_BEGIN_DT,
       DT_DIM.CAL_YR_WEEK_END_DT,
       DT_DIM.CAL_YR_MTH_N,
       DT_DIM.CAL_YR_MTH_NM,
       DT_DIM.CAL_YR_MTH_BEGIN_DT,
       DT_DIM.CAL_YR_MTH_END_DT,
       DT_DIM.CAL_YR_MTH,
       DT_DIM.CAL_YR_QTR_N,
       DT_DIM.CAL_YR_QTR_BEGIN_DT,
       DT_DIM.CAL_YR_QTR_END_DT,
       DT_DIM.CAL_YR_QTR,
       DT_DIM.CAL_YR_BEGIN_DT,
       DT_DIM.CAL_YR_END_DT,
       DT_DIM.CAL_YR,
       DT_DIM.OPRS_HOLIDAY_IND,
       DT_DIM.FDC_NON_WRK_IND,
       RCPT_TY_DIM.RCPT_TY_ID,
       RCPT_TY_DIM.RCPT_TY_CD,
       RCPT_TY_DIM.RCPT_TY_NM,
       RCPT_TY_DIM.RCPT_TY_GRP_CD,
       RCPT_TY_DIM.APPRV_REC_IND,
       WRHS_DIM.WRHS_ID,
       WRHS_DIM.WRHS_CD,
       CLIENT_PART_DIM.CLIENT_PART_ID,
       CLIENT_PART_DIM.PART_N,
       CLIENT_PART_DIM.PART_DESC,
       CLIENT_PART_DIM.PART_MASTER_MAKE,
       CLIENT_PART_DIM.PART_TY_CD,
       CLIENT_PART_DIM.PART_FAM_CD,
       CLIENT_PART_DIM.HOST_DAILY_INVN_SYNC_IND,
       CLIENT_PART_DIM.COLLTRL_IND,
       CLIENT_PART_DIM.VRTL_PART_IND,
       CLIENT_PART_DIM.RPR_PART_MODEL,
       CLIENT_PART_DIM.RPR_PART_MAKE,
       CLIENT_PART_DIM.RPR_PRIM_MODEL,
       CLIENT_PART_DIM.PART_COLOR,
       CLIENT_PART_DIM.PART_SPPL_CD,
       CLIENT_PART_DIM.PART_SPPL_NM,
       CLIENT_PART_DIM.PART_COST,
       INVN_STAT_DIM.INVN_STAT_ID,
       INVN_STAT_DIM.INVN_STAT_CD,
       INVN_STAT_DIM.INVN_STAT_NM,
       INVN_STAT_DIM.HOST_INVN_STAT_CD,
       RMA_RTRN_CD_DIM.RMA_RTRN_CD_KEY,
       RMA_RTRN_CD_DIM.RMA_RTRN_CD_ID,
       RMA_RTRN_CD_DIM.RMA_RTRN_CD,
       RMA_RTRN_CD_DIM.RMA_RTRN_CD_NM,
       RMA_RTRN_RSN_DIM.RMA_RTRN_RSN_KEY,
       RMA_RTRN_RSN_DIM.RMA_RTRN_RSN_ID,
       RMA_RTRN_RSN_DIM.RMA_RTRN_RSN_CD,
       RMA_RTRN_RSN_DIM.RMA_RTRN_RSN_NM,
       STOR_LOC_DIM.STOR_LOC_KEY,
       STOR_LOC_DIM.STOR_LOC_ID,
       STOR_LOC_DIM.STOR_LOC_CD,
       STOR_LOC_DIM.STOR_AREA_CD,
       STOR_LOC_DIM.BLDG_CD,
       STOR_LOC_DIM.STOR_AREA_4_WALLS_INVN_IND,
       STOR_LOC_DIM.STOR_AREA_VRTL_BIN_IND,
       STOR_LOC_DIM.STOR_AREA_SGN_IND,
       STOR_LOC_DIM.STOR_AREA_PICK_IND,
       SRC_SYS_USER_DIM.SRC_SYS_USER_KEY,
       SRC_SYS_USER_DIM.SRC_SYS_USER_ID,
       SRC_SYS_USER_DIM.SRC_SYS_USER_CD,
       RMA_TY_DIM.RMA_TY_KEY,
       RMA_TY_DIM.RMA_TY_ID,
       RMA_TY_DIM.RMA_TY_CD,
       RMA_TY_DIM.RMA_TY_NM,
       RMA_INDS_DIM.RMA_INDS_KEY,
       RMA_INDS_DIM.BUYER_REMORSE_PER_IND,
       RMA_INDS_DIM.PART_OVRRD_ALLOW_IND,
       RMA_INDS_DIM.DEVALD_PART_OVRRD_ALLOW_IND,
       RMA_INDS_DIM.SERIAL_OVRRD_ALLOW_IND,
       RMA_INDS_DIM.UNDER_WRRNT_IND,
       RMA_INDS_DIM.RMA_SPECIAL_PROC_IND,
       RMA_INDS_DIM.RTRN_LABEL_PRINT_IND,
       RMA_INDS_DIM.MULT_RECENT_SHIP_IND,
       RMA_INDS_DIM.MULT_RTRN_UNIT_IND,
       RMA_INDS_DIM.BOM_IND,
       RMA_SALES_CHNL_DIM.RMA_SALES_CHNL_KEY,
       RMA_SALES_CHNL_DIM.RMA_SALES_CHNL_ID,
       RMA_SALES_CHNL_DIM.RMA_SALES_CHNL_CD,
       RMA_SALES_CHNL_DIM.RMA_SALES_CHNL_NM,
       RMA_RESHIP_RJCT_DIM.RMA_RESHIP_RJCT_ID,
       RMA_RESHIP_RJCT_DIM.RMA_RESHIP_RJCT_CD,
       RMA_RESHIP_RJCT_DIM.RMA_RESHIP_RJCT_NM,
       RMA_KIT_INDS_DIM.RMA_KIT_INDS_KEY,
       RMA_KIT_INDS_DIM.KIT_NO_PROOF_OF_PURCH_IND,
       RMA_KIT_INDS_DIM.KIT_NO_CHRGR_IND,
       RMA_KIT_INDS_DIM.KIT_NO_BATTERY_IND,
       RMA_KIT_INDS_DIM.KIT_NO_BACK_COVER_IND,
       RMA_KIT_INDS_DIM.KIT_NO_GIFT_BOX_IND,
       RMA_KIT_INDS_DIM.KIT_NO_EARBUDS_IND,
       RMA_KIT_INDS_DIM.KIT_NO_COLLTRL_IND,
       RMA_KIT_INDS_DIM.KIT_NO_CMPNT_IND,
       RMA_RTRN_TY_DIM.RMA_RTRN_TY_KEY,
       RMA_RTRN_TY_DIM.RMA_RTRN_TY_ID,
       RMA_RTRN_TY_DIM.RMA_RTRN_TY_CD,
       RMA_RTRN_TY_DIM.RMA_RTRN_TY_NM,
       CLIENT_DIM.CLIENT_ID,
       CLIENT_DIM.CLIENT_CD,
       CLIENT_DIM.CLIENT_NM,
       RMA_PIECE_RCPT_TX_F.PIECE_ID,
       RMA_PIECE_RCPT_TX_F.RMA_ADD_DT_KEY,
       RMA_PIECE_RCPT_TX_F.RMA_ACT_DT_KEY
FROM (((((((((((((((EDW.RMA_PIECE_RCPT_TX_F RMA_PIECE_RCPT_TX_F
                    INNER JOIN
                    EDW.CLIENT_DIM CLIENT_DIM
                    ON (RMA_PIECE_RCPT_TX_F.CLIENT_KEY =
                        CLIENT_DIM.CLIENT_KEY))
                   INNER JOIN
                   EDW.RMA_RESHIP_RJCT_DIM RMA_RESHIP_RJCT_DIM
                   ON (RMA_PIECE_RCPT_TX_F.RMA_RESHIP_RJCT_KEY =
                       RMA_RESHIP_RJCT_DIM.RMA_RESHIP_RJCT_KEY))
                  INNER JOIN
                  EDW.DT_DIM DT_DIM
                  ON (RMA_PIECE_RCPT_TX_F.RCPT_DT_KEY = DT_DIM.DT_KEY))
                 INNER JOIN
                 EDW.RCPT_TY_DIM RCPT_TY_DIM
                 ON (RMA_PIECE_RCPT_TX_F.RCPT_TY_KEY =
                     RCPT_TY_DIM.RCPT_TY_KEY))
                INNER JOIN
                EDW.CLIENT_PART_DIM CLIENT_PART_DIM
                ON (RMA_PIECE_RCPT_TX_F.DEVALD_CLIENT_PART_KEY =
                    CLIENT_PART_DIM.CLIENT_PART_KEY))
               INNER JOIN
               EDW.INVN_STAT_DIM INVN_STAT_DIM
               ON (RMA_PIECE_RCPT_TX_F.INVN_STAT_KEY =
                   INVN_STAT_DIM.INVN_STAT_KEY))
              INNER JOIN
              EDW.WRHS_DIM WRHS_DIM
              ON (INVN_STAT_DIM.WRHS_KEY = WRHS_DIM.WRHS_KEY))
             INNER JOIN
             EDW.RMA_RTRN_CD_DIM RMA_RTRN_CD_DIM
             ON (RMA_PIECE_RCPT_TX_F.RMA_RTRN_CD_KEY =
                 RMA_RTRN_CD_DIM.RMA_RTRN_CD_KEY))
            INNER JOIN
            EDW.STOR_LOC_DIM STOR_LOC_DIM
            ON (RMA_PIECE_RCPT_TX_F.STOR_LOC_KEY = STOR_LOC_DIM.STOR_LOC_KEY))
           INNER JOIN
           EDW.RMA_TY_DIM RMA_TY_DIM
           ON (RMA_PIECE_RCPT_TX_F.RMA_TY_KEY = RMA_TY_DIM.RMA_TY_KEY))
          INNER JOIN
          EDW.RMA_INDS_DIM RMA_INDS_DIM
          ON (RMA_PIECE_RCPT_TX_F.RMA_INDS_KEY = RMA_INDS_DIM.RMA_INDS_KEY))
         INNER JOIN
         EDW.RMA_SALES_CHNL_DIM RMA_SALES_CHNL_DIM
         ON (RMA_PIECE_RCPT_TX_F.RMA_SALES_CHNL_KEY =
             RMA_SALES_CHNL_DIM.RMA_SALES_CHNL_KEY))
        INNER JOIN
        EDW.RMA_RTRN_TY_DIM RMA_RTRN_TY_DIM
        ON (RMA_PIECE_RCPT_TX_F.RMA_RTRN_TY_KEY =
            RMA_RTRN_TY_DIM.RMA_RTRN_TY_KEY))
       INNER JOIN
       EDW.SRC_SYS_USER_DIM SRC_SYS_USER_DIM
       ON (RMA_PIECE_RCPT_TX_F.SRC_SYS_USER_KEY =
           SRC_SYS_USER_DIM.SRC_SYS_USER_KEY))
      INNER JOIN
      EDW.RMA_KIT_INDS_DIM RMA_KIT_INDS_DIM
      ON (RMA_PIECE_RCPT_TX_F.RMA_KIT_INDS_KEY =
          RMA_KIT_INDS_DIM.RMA_KIT_INDS_KEY))
     INNER JOIN EDW.RMA_RTRN_RSN_DIM RMA_RTRN_RSN_DIM
        ON (RMA_PIECE_RCPT_TX_F.RMA_RTRN_RSN_KEY =
            RMA_RTRN_RSN_DIM.RMA_RTRN_RSN_KEY)
WHERE (DT_DIM.CAL_YR_MTH = '202012') AND (CLIENT_DIM.CLIENT_ID = 'TMO')